sudo: required
language: bash
services:
  - docker

env:
  global:
    - VERSION=2.7.1
  matrix:
    - DOCKER=service
      DOCKER_BUILD=biggis/hdfs:${VERSION}
      DOCKERFILE=Dockerfile
    - DOCKER=client
      DOCKER_BUILD=biggis/hdfs-client:${VERSION}
      DOCKERFILE=Dockerfile.client
    - DOCKER=client
      DOCKER_BUILD=biggis/hdfs-client-webhdfs:${VERSION}
      DOCKERFILE=Dockerfile.webhdfs
      DOCKERFILE=Dockerfile.webhdfs

install:
  #login to dockerhub
  - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD

script:
  #build the images
  - docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` -t ${DOCKER_BUILD} -f ${DOCKERFILE} .

after_success:
  - echo "build successful"
  #push the image to dockerhub
  - docker push ${DOCKER_BUILD}
