sudo: required
language: bash
services:
  - docker

env:
  global:
    - IMG_HDFS=biggis/hdfs:2.7.1
    - IMG_HDFS_CLIENT=biggis/hdfs-client:2.7.1
    - IMG_HDFS_CLIENT_WEBHDFS=biggis/hdfs-client-webhdfs:2.7.1
    - IMG_HDFS_API=biggis/hdfs-api

install:
  #login to dockerhub
  - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD

script:
  #build the images
  - docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` -t $IMG_HDFS .
  - docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` -t $IMG_HDFS_API -f Dockerfile.api .
  - docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` -t $IMG_HDFS_CLIENT -f deprecated/Dockerfile.client .
  - docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` -t $IMG_HDFS_CLIENT_WEBHDFS -f deprecated/Dockerfile.webhdfs .

after_success:
  - echo "build successful"
  #push the image to dockerhub
  - docker push $IMG_HDFS
  - docker push $IMG_HDFS_CLIENT
  - docker push $IMG_HDFS_CLIENT_WEBHDFS
  - docker push IMG_HDFS_API
