version: '2.1'

services:
  hdfs-client:
    image: biggis/hdfs-client:2.7.1
    command: execute.sh -copyFromLocal /data/hdfs/hamlet.txt /
    environment:
      USER_ID: ${USER_ID-1000}
      USER_NAME: hdfs
      HADOOP_MASTER_ADDRESS: hdfs-name
      TIMEZONE: Europe/Berlin
    volumes:
      - ./data/hamlet.txt:/data/hdfs/hamlet.txt
