version: '2.1'

services:
  hdfs-name:
    image: biggis/hdfs:2.7.1
    ports:
      - "50070:50070"
      - "8020:8020"
    command: start.sh name
    environment:
      USER_ID: ${USER_ID-1000}
      USER_NAME: hdfs
      HADOOP_MASTER_ADDRESS: hdfs-name
      TIMEZONE: Europe/Berlin
    # volumes:
    #   - hdfs-data:/data/hdfs

  hdfs-sname:
    image: biggis/hdfs:2.7.1
    depends_on:
        - hdfs-name
    ports:
      - "50090:50090"
    command: start.sh sname
    environment:
      USER_ID: ${USER_ID-1000}
      USER_NAME: hdfs
      HADOOP_MASTER_ADDRESS: hdfs-name
      TIMEZONE: Europe/Berlin
    # volumes:
    #   - hdfs-data:/data/hdfs

  hdfs-data:
    image: biggis/hdfs:2.7.1
    depends_on:
        - hdfs-name
    expose:
      - "50010"
      - "50075"
    command: start.sh data
    environment:
      USER_ID: ${USER_ID-1000}
      USER_NAME: hdfs
      HADOOP_MASTER_ADDRESS: hdfs-name
      TIMEZONE: Europe/Berlin
#     volumes:
#       - hdfs-data:/data/hdfs
#
# volumes:
#   hdfs-data:
